name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Kind Kubernetes cluster
        run: kind create cluster

      - name: Setup MetalLB
        run: |
          kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml
          kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml
          kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
          kubectl apply -f metallb-config.yaml

      - name: Test setup
        run: |
          kubectl apply -f nginx.yaml
          sleep 30
          kubectl get all
          kubectl wait -l app=nginx --for=condition=Ready --timeout=120s deployment
          kubectl get svc