name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Kind Kubernetes cluster
        run: kind create cluster

      - name: Setup MetalLB
        run: |
          kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml
          kubectl -n metallb-system create secret generic memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
          kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml

          sleep 60
          kubectl -n metallb-system get all
          kubectl -n metallb-system describe pod $(kubectl -n metallb-system get pod -l app=metallb -o jsonpath='{.items[0].metadata.name}')
          kubectl -n metallb-system wait --for=condition=Ready --timeout=120s deployment -l app=metallb

          kubectl apply -f metallb-config.yaml
          sleep 30

      - name: Test setup
        run: |
          kubectl apply -f nginx.yaml
          sleep 30
          kubectl get all
          kubectl wait --for=condition=Ready --timeout=120s deployment -l app=nginx
          kubectl get svc